tiles: "OSM"

tech_colors:
  # wind
  onwind: "#235ebc"
  onshore wind: "#235ebc"
  offwind: "#6895dd"
  offshore wind: "#6895dd"
  offwind-ac: "#6895dd"
  offshore wind (AC): "#6895dd"
  offwind-dc: "#74c6f2"
  offshore wind (DC): "#74c6f2"
  # water
  hydro: "#298c81"
  hydro reservoir: "#298c81"
  ror: "#3dbfb0"
  run of river: "#3dbfb0"
  hydroelectricity: "#298c81"
  PHS: "#51dbcc"
  wave: "#a7d4cf"
  # solar
  solar: "#f9d002"
  solar PV: "#f9d002"
  solar thermal: "#ffbf2b"
  solar rooftop: "#ffea80"
  # gas
  OCGT: "#e0986c"
  OCGT marginal: "#e0986c"
  OCGT-heat: "#e0986c"
  gas boiler: "#db6a25"
  gas boilers: "#db6a25"
  gas boiler marginal: "#db6a25"
  gas: "#e05b09"
  fossil gas: "#e05b09"
  natural gas: "#e05b09"
  CCGT: "#a85522"
  CCGT marginal: "#a85522"
  gas for industry co2 to atmosphere: "#692e0a"
  gas for industry co2 to stored: "#8a3400"
  gas for industry: "#853403"
  gas for industry CC: "#692e0a"
  gas pipeline: "#ebbca0"
  gas pipeline new: "#a87c62"
  # oil
  oil: "#c9c9c9"
  oil boiler: "#adadad"
  agriculture machinery oil: "#949494"
  agriculture machinery: "#abdeff"
  shipping oil: "#808080"
  land transport oil: "#afafaf"
  # nuclear
  Nuclear: "#ff8c00"
  Nuclear marginal: "#ff8c00"
  nuclear: "#ff8c00"
  uranium: "#ff8c00"
  # coal
  Coal: "#545454"
  coal: "#545454"
  Coal marginal: "#545454"
  solid: "#545454"
  Lignite: "#826837"
  lignite: "#826837"
  Lignite marginal: "#826837"
  # biomass
  biogas: "#e3d37d"
  biogas upgrading: "#e3d37d"
  biomass: "#baa741"
  solid biomass: "#baa741"
  solid biomass CHP: "#baa741"
  solid biomass transport: "#baa741"
  solid biomass for industry: "#7a6d26"
  solid biomass for industry CC: "#47411c"
  solid biomass CHP CC: "#aeb841"
  solid biomass for industry co2 from atmosphere: "#736412"
  solid biomass for industry co2 to stored: "#47411c"
  # power transmission
  lines: "#6c9459"
  transmission lines: "#6c9459"
  electricity distribution grid: "#97ad8c"
  # electricity demand
  Electric load: "#110d63"
  electric demand: "#110d63"
  electricity: "#110d63"
  industry electricity: "#2d2a66"
  industry new electricity: "#2d2a66"
  agriculture electricity: "#494778"
  agriculture: "#494778"
  # battery + EVs
  battery: "#ace37f"
  battery storage: "#ace37f"
  home battery: "#80c944"
  home battery storage: "#80c944"
  BEV charger: "#baf238"
  V2G: "#e5ffa8"
  land transport EV: "#baf238"
  Li ion: "#baf238"
  # hot water storage
  water tanks: "#e69487"
  hot water storage: "#e69487"
  hot water charging: "#e69487"
  hot water discharging: "#e69487"
  # heat demand
  Heat load: "#cc1f1f"
  heat: "#cc1f1f"
  heat demand: "#cc1f1f"
  rural heat: "#ff5c5c"
  central heat: "#cc1f1f"
  decentral heat: "#750606"
  low-temperature heat for industry: "#8f2727"
  process heat: "#ff0000"
  agriculture heat: "#d9a5a5"
  # heat supply
  heat pumps: "#2fb537"
  heat pump: "#2fb537"
  air heat pump: "#36eb41"
  ground heat pump: "#2fb537"
  Ambient: "#98eb9d"
  gas CHP: "#8a5751"
  CHP: "#8a5751"
  gas CHP CC: "#634643"
  CHP CC: "#634643"
  CHP heat: "#8a5751"
  CHP electric: "#8a5751"
  district heating: "#e8beac"
  resistive heater: "#d8f9b8"
  retrofitting: "#8487e8"
  building retrofitting: "#8487e8"
  # hydrogen
  H2 for industry: "#f073da"
  H2 for shipping: "#ebaee0"
  H2: "#bf13a0"
  hydrogen: "#bf13a0"
  SMR: "#870c71"
  SMR CC: "#4f1745"
  steam methane reforming: "#870c71"
  steam methane reforming CC: "#4f1745"
  H2 liquefaction: "#d647bd"
  hydrogen storage: "#bf13a0"
  H2 storage: "#bf13a0"
  land transport fuel cell: "#6b3161"
  H2 pipeline: "#f081dc"
  H2 pipeline retrofitted: "#ba99b5"
  H2 Fuel Cell: "#c251ae"
  H2 Electrolysis: "#ff29d9"
  power-to-hydrogen: "#ff29d9"
  # syngas
  Sabatier: "#9850ad"
  methanation: "#c44ce6"
  methane: "#c44ce6"
  helmeth: "#e899ff"
  # synfuels
  Fischer-Tropsch: "#25c49a"
  liquid: "#25c49a"
  kerosene for aviation: "#a1ffe6"
  aviation fuels: "#a1ffe6"
  naphtha for industry: "#57ebc4"
  methanolisation: "#83d6d5"
  methanol: "#468c8b"
  shipping methanol: "#468c8b"
  shipping fuels: "#468c8b"
  shipping methanol emissions: "#468c8b"
  methanol emissions: "#468c8b"
  # co2
  CC: "#f29dae"
  carbon capture: "#f29dae"
  CCS: "#f29dae"
  CO2 sequestration: "#f29dae"
  DAC: "#ff5270"
  direct air capture: "#ff5270"
  co2 stored: "#f2385a"
  co2: "#f29dae"
  co2 vent: "#ffd4dc"
  CO2 pipeline: "#f5627f"
  # emissions
  process emissions CC: "#000000"
  process emissions: "#222222"
  process emissions to stored: "#444444"
  process emissions to atmosphere: "#888888"
  oil emissions: "#aaaaaa"
  liquid hydrocarbons emissions: "#aaaaaa"
  shipping oil emissions: "#555555"
  land transport oil emissions: "#777777"
  agriculture machinery oil emissions: "#333333"
  # other
  shipping: "#03a2ff"
  power-to-heat: "#2fb537"
  power-to-gas: "#c44ce6"
  power-to-H2: "#ff29d9"
  power-to-liquid: "#25c49a"
  gas-to-power/heat: "#ee8340"
  waste: "#e3d37d"
  other: "#000000"
  import pipeline-h2: "#fff6e0"
  import shipping-lh2: "#ebe1ca"
  import shipping-lch4: "#d6cbb2"
  import shipping-ftfuel: "#bdb093"
  import hvdc: "#91856a"
  fossil oil and gas: "#ababab"
  green e-fuel imports: "#03a2ff"
preferred_order:
  - H2 storage
  - hydrogen storage
  - battery storage
  - BEV charger
  - V2G
  - hot water storage
  - co2
  - hydroelectricity
  - hydro reservoir
  - pumped hydro storage
  - run of river
  - transmission lines
  - electricity distribution grid
  - solid biomass
  - biogas
  - onshore wind
  - offshore wind
  - offshore wind (AC)
  - offshore wind (DC)
  - solar PV
  - solar thermal
  - solar rooftop
  - solar
  - building retrofitting" "ground heat pump
  - air heat pump
  - heat pump
  - resistive heater
  - power-to-heat
  - gas-to-power/heat
  - CHP
  - OCGT
  - gas boiler
  - gas
  - natural gas
  - helmeth
  - methanation
  - power-to-gas
  - power-to-H2
  - H2 pipeline
  - H2 pipeline retrofitted
  - gas pipeline
  - gas pipeline new
  - H2 liquefaction
  - power-to-liquid
  - CO2 sequestration
  - CCS

operation:
  carrier:
    total-electricity: Total Electricity
    total-heat: Total Heating
    H2: Hydrogen
    gas: Methane
    total-liquid-hydrocarbons: Liquid Hydrocarbons
    co2 stored: Stored Carbon Dioxide
    co2: Carbon Dioxide
    # AC: High Voltage Electricity
    # low voltage: Low Voltage Electricity
    # urban central heat: Urban Central Heating
    # residential rural heat: Residential Rural Building Heating
    # methanol: Methanol
    # oil: Liquid Hydrocarbons
  resolution:
    # 3H: 3-hourly
    24H: daily
    # 168H: weekly

scenarios:
  costs: Total System Costs (bnâ‚¬/a)
  generation: Generation Capacities (GW)
  storage: Storage Capacities (TWh)
  conversion: Conversion Capacities (GW)
  energy: Energy Balance (TWh/a)
  co2: Carbon Dioxide Balance (MtCO2/a)
  # hydrogen: Hydrogen Balance (TWh/a)

ylim:
  costs: [0, 1000]
  generation: [0, 7000]
  storage: [0, 200]
  conversion: [0, 11000]
  energy: [-15000, 15000]
  co2: [-600, 600]

scenario_names:
  NG: Nigeria
  NG_no_oil: Nigeria without oil
  MA: Morocco

########## spatial parameters

spatial_parameters:
  cf:
    nice_name: Capacity Factor
    unit: "%" 
  p_nom:
    nice_name: Optimal Nominal Power
    unit: (MW)
  p_nom_opt:
    nice_name: Original Nominal Power
    unit: (MW)
  marginal_cost:
    nice_name: Cost During Production
    unit: (euro/MWh)
  capital_cost:
    nice_name: Cost Of Expanding Generation
    unit: (euro/MW)
  bus_load:
    nice_name: Electricity Load
    unit: (MW)    

network_parameters:
  total_capacity: Total Capacity (MVA)
  reinforcement: Reinforcement (MVA)
  original_capacity: Original Capacity (MVA)
  max_capacity: Maximum Capacity (MVA)
  length: Line Length (km)

carrier:
  CCGT: Combined-Cycle Gas
  biomass: Biomass
  offwind-ac: Offshore Wind (AC)
  geothermal: Geothermal
  coal: Coal
  oil: Oil
  solar: Solar
  OCGT: Open-Cycle Gas
  nuclear: Nuclear
  onwind: Onshore Wind
  offwind-dc: Offshore Wind (DC)
  lignite: Lignite
  hydro: Reservoir & Dam
  PHS: Pumped Hydro Storage
  ror: Run of River
  H2: Hydrogen Storage
  battery: Battery Storage
  load: Load

# https://holoviews.org/user_guide/Colormaps.html
# you can also pick you own colors
carrier_colors:
  CCGT: Purples
  oil: Greys
  solar: YlOrBr
  onwind: Blues
  ror: BuPu
  OCGT: Oranges
  coal: PuBuGn
  biomass: Reds
  offwind-ac: Reds
  geothermal: Reds
  nuclear: Reds
  offwind-dc: Reds
  lignite: Reds
  hydro: Reds
  PHS: Reds
  H2: Reds
  battery: Reds

######### system operation parameters

gen_t_parameter:
  p:
    nice_name: Supply
    unit: MW
    legend_title: " "
  p_max_pu:
    nice_name: Maximum Output Possible Per Unit Nominal Power
    unit: MW
    legend_title: " "

storage_t_parameter:
  p:
    nice_name: Active Power
    unit: MW
    legend_title: Region Number and Storage Type
  inflow:
    nice_name: Inflow To State Of Charge
    unit: MW
    legend_title: Region Number and Storage Type
  spill:
    nice_name: Spillage For Each Snapshot
    unit: MW
    legend_title: Region Number and Storage Type
  state_of_charge:
    nice_name: State Of Charge
    unit: MWh
    legend_title: Region Number and Storage Type

links_t_parameter:
  p0:
    nice_name: Demand
    unit: MW
    legend_title: " "
  mu_upper:
    nice_name: Shadow Price Of Maximum Nominal Power
    unit: euro/MW
    legend_title: " "
  mu_lower:
    nice_name: Shadow Price Of Minimum Nominal Power
    unit: euro/MW
    legend_title: " "

########### SCENARIO COMPARISION parameters

statistics_param_units:
  Capacity Factor: Capacity factor, %
  Capital Expenditure: Euro
  Curtailment: MW
  Installed Capacity: MW
  Operational Expenditure: Euro
  Optimal Capacity: MW
  Revenue: Euro
  Supply: MW-hours
  Withdrawal: Euro

second_param_units:
  CO2 emissions: MtCO2
  # TODO Would be worth discussing which parameter does make sense as a second option
  # strictly speaking, we have Optimal Capacity in the droplist above
  # but agree that it may be worth to have a visual comparison
  Optimal Capacity: MW
